[package]
name = "genesis-tools"
version = "0.1.0"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.2.2", features = ["derive", "env", "suggestions"] }
anyhow = { workspace = true }

# TODO: Gokhan, need help here:
# want to import the recovery json parsing tool from here.
# https://github.com/0o-de-lally/libra/blob/dc5f26debb76c75f83359ba80c2bdd010d13c719/ol/types/src/legacy_recovery.rs#L313

# ol-genesis-tools = { git = "https://github.com/0o-de-lally/libra.git"}
